# Generated by Django 5.0.1 on 2024-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=40)),
                ('lup', models.DateTimeField()),
                ('lact', models.CharField(max_length=60)),
                ('mtype', models.CharField(max_length=20)),
                ('mcode', models.CharField(max_length=30)),
                ('mq', models.CharField(max_length=20)),
                ('mdesc', models.CharField(max_length=50)),
                ('mlayers', models.IntegerField()),
                ('mweight', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bin',
            },
        ),
        migrations.CreateModel(
            name='Bund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField()),
                ('bno', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bund',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('nam', models.CharField(max_length=10)),
                ('dip', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=20)),
                ('madd', models.CharField(max_length=30)),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('upd', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('dno', models.IntegerField()),
                ('din', models.IntegerField()),
                ('ino', models.IntegerField()),
                ('mcap', models.CharField(max_length=10)),
                ('mdesc', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('avp', models.CharField(max_length=20)),
                ('sno', models.DecimalField(decimal_places=10, max_digits=20)),
                ('dq', models.CharField(max_length=20)),
                ('mcode', models.CharField(max_length=30)),
                ('dstatus', models.CharField(max_length=30)),
                ('ttime', models.DateTimeField()),
            ],
            options={
                'db_table': 'dispatch',
            },
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10)),
                ('tname', models.CharField(max_length=20)),
                ('tmax', models.CharField(max_length=10)),
                ('gid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gps',
            },
        ),
        migrations.CreateModel(
            name='Heo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=10)),
                ('ct', models.CharField(max_length=10)),
                ('mve', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'heo',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('platform', models.CharField(max_length=100)),
                ('h_number', models.CharField(max_length=150)),
                ('Status', models.CharField(max_length=150)),
                ('count', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hook',
            },
        ),
        migrations.CreateModel(
            name='Inb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(unique=True)),
                ('dt', models.DateTimeField()),
                ('ct', models.CharField(max_length=40)),
                ('zone', models.CharField(max_length=50)),
                ('sour', models.CharField(max_length=40)),
                ('bi', models.CharField(max_length=30)),
                ('truck', models.CharField(max_length=30)),
                ('asign', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('bns', models.CharField(max_length=40)),
                ('tp', models.CharField(max_length=20)),
                ('mcode', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'inb',
            },
        ),
        migrations.CreateModel(
            name='Inboundtruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(unique=True)),
                ('dt', models.DateTimeField()),
                ('sour', models.CharField(max_length=40)),
                ('bi', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=50)),
                ('truck', models.CharField(max_length=30)),
                ('asign', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inboundtruck',
            },
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid', models.CharField(max_length=10)),
                ('lstart', models.CharField(max_length=30)),
                ('lend', models.CharField(max_length=30)),
                ('c1', models.CharField(max_length=20)),
                ('c2', models.CharField(max_length=10)),
                ('stat', models.IntegerField()),
            ],
            options={
                'db_table': 'loc',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(max_length=40)),
                ('val', models.CharField(max_length=30)),
                ('ord', models.IntegerField()),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('mcode', models.CharField(max_length=30)),
                ('mdesc', models.CharField(max_length=30)),
                ('aweight', models.CharField(max_length=30)),
                ('cweight', models.CharField(max_length=30)),
                ('cstock', models.CharField(max_length=30)),
                ('ptype', models.CharField(max_length=30)),
                ('crt', models.CharField(max_length=30)),
                ('dte', models.DateField()),
                ('tm', models.TimeField()),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Mcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField()),
                ('mcode', models.IntegerField()),
            ],
            options={
                'db_table': 'mcode',
            },
        ),
        migrations.CreateModel(
            name='Mp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField()),
                ('dt', models.DateTimeField()),
                ('mcode', models.CharField(max_length=20)),
                ('sour', models.CharField(max_length=40)),
                ('bi', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=50)),
                ('truck', models.CharField(max_length=30)),
                ('asign', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('bn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mp',
            },
        ),
        migrations.CreateModel(
            name='Mt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('mcode', models.CharField(max_length=30)),
                ('mdesc', models.CharField(max_length=30)),
                ('aweight', models.CharField(max_length=30)),
                ('cweight', models.CharField(max_length=30)),
                ('cstock', models.CharField(max_length=30)),
                ('ptype', models.CharField(max_length=30)),
                ('crt', models.CharField(max_length=30)),
                ('dte', models.DateField()),
                ('tm', models.TimeField()),
            ],
            options={
                'db_table': 'mt',
            },
        ),
        migrations.CreateModel(
            name='Mtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=10)),
                ('nam', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mtu',
            },
        ),
        migrations.CreateModel(
            name='Rake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt', models.CharField(max_length=10)),
                ('ino', models.IntegerField()),
                ('desti', models.CharField(max_length=30)),
                ('stat', models.CharField(max_length=10)),
                ('rcont', models.IntegerField()),
            ],
            options={
                'db_table': 'rake',
            },
        ),
        migrations.CreateModel(
            name='Rke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(unique=True)),
                ('dt', models.DateTimeField()),
                ('sour', models.CharField(max_length=40)),
                ('wname', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=50)),
                ('truck', models.CharField(max_length=30)),
                ('asign', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('bn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'rke',
            },
        ),
        migrations.CreateModel(
            name='Truckdispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(unique=True)),
                ('dt', models.DateTimeField()),
                ('val', models.CharField(max_length=40)),
                ('zone', models.CharField(max_length=50)),
                ('sour', models.CharField(max_length=40)),
                ('bi', models.CharField(max_length=30)),
                ('truck', models.CharField(max_length=30)),
                ('asign', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'truckdispatch',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=200)),
                ('gr', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('val', models.IntegerField()),
                ('ac', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=10)),
                ('vname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Wagn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ino', models.IntegerField()),
                ('dcode', models.CharField(max_length=5)),
                ('wname', models.CharField(max_length=20)),
                ('wtype', models.CharField(max_length=10)),
                ('mcode', models.CharField(max_length=20)),
                ('sto', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=10)),
                ('whealth', models.CharField(max_length=10)),
                ('od', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'wagn',
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('h_number', models.CharField(max_length=100)),
                ('wname', models.CharField(max_length=100)),
                ('cod', models.CharField(max_length=120)),
                ('de', models.CharField(max_length=100)),
                ('wt', models.CharField(max_length=100)),
                ('stat', models.CharField(max_length=100)),
                ('st', models.CharField(max_length=100)),
                ('od', models.IntegerField()),
            ],
            options={
                'db_table': 'wagon',
            },
        ),
        migrations.CreateModel(
            name='Workoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(unique=True)),
                ('dt', models.DateTimeField()),
                ('stat', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Od',
            },
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'yourmodel',
            },
        ),
    ]
