# Generated by Django 5.0.1 on 2024-04-20 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tme',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
