# Generated by Django 5.0.1 on 2024-04-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0002_user_tme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strt', models.CharField(max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('ed', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'map',
            },
        ),
    ]
