# Generated by Django 5.0.1 on 2024-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0003_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=200)),
                ('t', models.DateTimeField(default='0:0:00 12-2-2000')),
            ],
            options={
                'db_table': 'mseg',
            },
        ),
    ]
