# Generated by Django 5.0.1 on 2024-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0004_mseg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worder', models.IntegerField()),
                ('val', models.IntegerField()),
            ],
            options={
                'db_table': 'ordstat',
            },
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
