# Generated by Django 5.0.1 on 2024-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0005_ordstat_delete_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='mseg',
            name='c',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
