# Generated by Django 5.0.1 on 2024-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0006_mseg_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='rake',
            name='asgn',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
