# Generated by Django 5.0.1 on 2024-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0007_rake_asgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='Status',
            field=models.CharField(default='PLAN', max_length=150),
        ),
        migrations.AlterField(
            model_name='hook',
            name='platform',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
