# Generated by Django 5.0.1 on 2024-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0008_alter_hook_status_alter_hook_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='platform',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
