# Generated by Django 5.0.1 on 2024-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0010_alter_hook_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt',
            name='grcode',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='grcodedes',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='lcode',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='lcodedes',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='mtype',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='scodedes',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='seccode',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mt',
            name='secodedes',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
