# Generated by Django 5.0.1 on 2024-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0011_mt_grcode_mt_grcodedes_mt_lcode_mt_lcodedes_mt_mtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dno',
            field=models.BigIntegerField(),
        ),
    ]
