# Generated by Django 5.0.1 on 2024-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0012_alter_dispatch_dno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='din',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dq',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='ino',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='mcap',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='sno',
            field=models.BigIntegerField(),
        ),
    ]
