# Generated by Django 5.0.1 on 2024-04-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0014_rename_bi_inboundtruck_mdesc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundtruck',
            name='ono',
        ),
    ]
