# Generated by Django 5.0.1 on 2024-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0015_remove_inboundtruck_ono'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundtruck',
            name='nm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
