# Generated by Django 5.0.1 on 2024-04-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0018_dispatch_ono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hook',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='hook',
            name='h_number',
        ),
        migrations.RemoveField(
            model_name='hook',
            name='platform',
        ),
    ]
