# Generated by Django 5.0.1 on 2024-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdy', '0019_remove_hook_status_remove_hook_h_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='Status',
            field=models.CharField(default='PLAN', max_length=150),
        ),
        migrations.AddField(
            model_name='hook',
            name='h_number',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hook',
            name='platform',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
